#!/bin/bash

ONOS_DOCKER_NAME=${ONOS_DOCKER_NAME:-onos}
ONOS_IMG=${ONOS_IMG:-onosproject/onos:latest}

docker run -it --rm \
  --name $ONOS_DOCKER_NAME \
  -e ONOS_APPS \
  --network host \
  -v /tmp/onos:/root/onos/apache-karaf/data/tmp \
  $ONOS_IMG "$@"
