#!/bin/bash

PYTHON_DOCKER_NAME=${PYTHON_DOCKER_NAME:-python}
PYTHON_IMG=${PYTHON_IMG:-python:3.10-slim}
PYTHON_MOUNT_DIR=${PYTHON_MOUNT_DIR:-$PWD}

docker run --privileged -it --rm \
    --name $PYTHON_DOCKER_NAME \
    --network host \
    -v "$PYTHON_MOUNT_DIR":/workdir -w /workdir \
    $PYTHON_IMG python "$@"
